question_data = [
    {"category":"Science: Computers",
     "type":"boolean",
     "difficulty":"easy",
     "question":"The logo for Snapchat is a Bell.",
     "correct_answer":"False",
     "incorrect_answers":["True"]
     },
     {"category":"Science: Computers",
     "type":"boolean",
     "difficulty":"easy",
     "question":"&quot;HTML&quot; stands for Hypertext Markup Language.",
     "correct_answer":"True",
     "incorrect_answers":["False"]
     },
     {"category":"Science: Computers",
      "type":"boolean",
      "difficulty":"easy",
      "question":"The Windows 7 operating system has six main editions.",
      "correct_answer":"True",
      "incorrect_answers":["False"]
      },
      {"category":"Science: Computers",
       "type":"boolean",
       "difficulty":"easy",
       "question":"The Windows ME operating system was released in the year 2000.",
       "correct_answer":"True",
       "incorrect_answers":["False"]
       },
       {"category":"Science: Computers",
        "type":"boolean",
        "difficulty":"medium",
        "question":"The first dual-core CPU was the Intel Pentium D.",
        "correct_answer":"False",
        "incorrect_answers":["True"]
        },
        {"category":"Science: Computers",
        "type":"boolean",
        "difficulty":"medium",
        "question":"The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
        "correct_answer":"False",
        "incorrect_answers":["True"]
        },
        {"category":"Science: Computers",
        "type":"boolean",
        "difficulty":"medium",
        "question":"It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
        "correct_answer":"True","incorrect_answers":["False"]
        },
        {"category":"Science: Computers",
        "type":"boolean",
        "difficulty":"easy",
        "question":"Linux was first created as an alternative to Windows XP.",
        "correct_answer":"False","incorrect_answers":["True"]
        },
        {"category":"Science: Computers",
        "type":"boolean",
        "difficulty":"medium",
        "question":"A Boolean value of &quot;0&quot; represents which of these words?",
        "correct_answer":"False",
        "incorrect_answers":["True"]
        },
        {"category":"Science: Computers",
        "type":"boolean",
        "difficulty":"hard",
        "question":"The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
        "correct_answer":"True",
        "incorrect_answers":["False"]
       }
    ]